# -*- coding: utf-8 -*-
"""newpipeline1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HYh9QDM0LqjPPIbNMjMIEzgbVLlvTnKR
"""

# ── Install libraries ─────────────────────────────────────────────
!pip install xgboost scikit-learn pandas openpyxl joblib -q

import pandas as pd
import numpy as np
import joblib
import warnings
warnings.filterwarnings('ignore')

from xgboost import XGBRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import TimeSeriesSplit

# ── 1. Load dataset ──────────────────────────────────────────────
df = pd.read_excel('/content/energy_cost_physics_verified (1).xlsx')
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values('Date').reset_index(drop=True)
print("Loaded shape:", df.shape)
print("Date range:", df['Date'].min().date(), "to", df['Date'].max().date())

# ── 2. Clean column names ────────────────────────────────────────
df.columns = [c.replace('\n', '_').replace(' ', '_').replace('(','').replace(')','') for c in df.columns]

# ── 3. Drop unused columns ───────────────────────────────────────
drop_cols = ['Unit_Cost_Actual_LKR', 'Unit_Cost_Predicted_LKR',
             'Total_Cost_LKR', 'Total_Gen_GWh',
             'Synthetic?', 'Filled?', 'Reservoir_GWh']
df = df.drop(columns=[c for c in drop_cols if c in df.columns])

# ── 4. Convert GWh to MWh ────────────────────────────────────────
gwh_cols = ['Major_Hydro_GWh', 'Coal_GWh', 'Furnace_Oil_GWh',
            'Diesel_GWh', 'Naphtha_GWh', 'Wind_CEB_GWh', 'Wind_IPP_GWh',
            'Solar_Ground_GWh', 'Solar_Rooftop_GWh', 'Mini_Hydro_GWh']
existing_gwh = [c for c in gwh_cols if c in df.columns]
df[existing_gwh] = df[existing_gwh] * 1000

# ── 5. Rename columns ────────────────────────────────────────────
rename_map = {}
for col in df.columns:
    if 'Major_Hydro' in col: rename_map[col] = 'major_hydro'
    elif 'Coal_GWh' in col: rename_map[col] = 'coal'
    elif 'Furnace_Oil' in col: rename_map[col] = 'furnace_oil'
    elif 'Diesel_GWh' in col: rename_map[col] = 'diesel'
    elif 'Naphtha_GWh' in col: rename_map[col] = 'naphtha'
    elif 'Wind_CEB' in col: rename_map[col] = 'wind_ceb'
    elif 'Wind_IPP' in col: rename_map[col] = 'wind_ipp'
    elif 'Solar_Ground' in col: rename_map[col] = 'solar_ground'
    elif 'Solar_Rooftop' in col: rename_map[col] = 'solar_rooftop'
    elif 'Mini_Hydro' in col: rename_map[col] = 'mini_hydro'
    elif 'Reservoir_%' in col or 'Reservoir__' in col: rename_map[col] = 'reservoir_pct'
    elif 'Load_Demand' in col: rename_map[col] = 'load_demand'
    elif 'FO_Price' in col: rename_map[col] = 'fo_price'
    elif 'Coal_Price' in col: rename_map[col] = 'coal_price'
df = df.rename(columns=rename_map)

# ── 6. Combine sources ───────────────────────────────────────────
df['wind']          = df.get('wind_ceb', 0) + df.get('wind_ipp', 0)
df['solar']         = df.get('solar_ground', 0) + df.get('solar_rooftop', 0)
df['total_thermal'] = df.get('furnace_oil', 0) + df.get('diesel', 0) + df.get('naphtha', 0)
df['total_coal']    = df.get('coal', 0)

drop_raw = ['wind_ceb','wind_ipp','solar_ground','solar_rooftop',
            'furnace_oil','diesel','naphtha','coal']
df = df.drop(columns=[c for c in drop_raw if c in df.columns])

# ── 7. Season encoding ───────────────────────────────────────────
if 'Season' in df.columns:
    season_map = {'sw_monsoon': 0, 'ne_monsoon': 1, 'dry_inter': 2}
    df['season_encoded'] = df['Season'].map(season_map).fillna(0).astype(int)
    df = df.drop(columns=['Season'])

# ── 8. Lag features ──────────────────────────────────────────────
df['wind_lag1']       = df['wind'].shift(1)
df['solar_lag1']      = df['solar'].shift(1)
df['mini_hydro_lag1'] = df['mini_hydro'].shift(1)

# ── 9. Residual load ─────────────────────────────────────────────
df['residual_load'] = (df['load_demand'] - df['wind_lag1'] - df['solar_lag1']).clip(lower=0)

# ── 10. Calendar features ────────────────────────────────────────
df['dayofweek']  = df['Date'].dt.dayofweek
df['month']      = df['Date'].dt.month
df['quarter']    = df['Date'].dt.quarter
df['is_weekend'] = (df['dayofweek'] >= 5).astype(int)

# ── 11. Drop NaNs ────────────────────────────────────────────────
df = df.dropna().reset_index(drop=True)
print("After processing:", df.shape)

# ── 12. Features and targets ─────────────────────────────────────
features = [
    'load_demand', 'residual_load', 'reservoir_pct',
    'wind_lag1', 'solar_lag1', 'mini_hydro_lag1',
    'dayofweek', 'month', 'quarter', 'is_weekend',
    'season_encoded'
]
targets = ['major_hydro', 'total_coal', 'total_thermal']

X = df[features].values
Y = df[targets].values

# ══════════════════════════════════════════════════════════════════
# TIME SERIES CROSS VALIDATION
# ══════════════════════════════════════════════════════════════════

print("\n" + "="*65)
print("TIME SERIES CROSS VALIDATION")
print("="*65)

tscv = TimeSeriesSplit(n_splits=5)

cv_mae  = {t: [] for t in targets}
cv_rmse = {t: [] for t in targets}
cv_r2   = {t: [] for t in targets}

for fold, (train_idx, test_idx) in enumerate(tscv.split(X), 1):
    X_train, X_test = X[train_idx], X[test_idx]
    Y_train, Y_test = Y[train_idx], Y[test_idx]

    train_start = df['Date'].iloc[train_idx[0]].date()
    train_end   = df['Date'].iloc[train_idx[-1]].date()
    test_start  = df['Date'].iloc[test_idx[0]].date()
    test_end    = df['Date'].iloc[test_idx[-1]].date()

    scaler_fold  = StandardScaler()
    X_train_sc   = scaler_fold.fit_transform(X_train)
    X_test_sc    = scaler_fold.transform(X_test)

    model_fold = MultiOutputRegressor(
        XGBRegressor(
            n_estimators=500,
            learning_rate=0.05,
            max_depth=6,
            subsample=0.8,
            colsample_bytree=0.8,
            random_state=42,
            n_jobs=-1
        )
    )
    model_fold.fit(X_train_sc, Y_train)
    Y_pred = np.clip(model_fold.predict(X_test_sc), 0, None)

    print(f"\nFold {fold}")
    print(f"  Train: {train_start} → {train_end} ({len(train_idx)} days)")
    print(f"  Test:  {test_start} → {test_end} ({len(test_idx)} days)")
    print(f"  {'Target':<18} {'MAE':>10} {'RMSE':>10} {'R2':>8}")
    print(f"  {'-'*50}")

    for i, t in enumerate(targets):
        mae  = mean_absolute_error(Y_test[:, i], Y_pred[:, i])
        rmse = mean_squared_error(Y_test[:, i], Y_pred[:, i]) ** 0.5
        r2   = r2_score(Y_test[:, i], Y_pred[:, i])
        cv_mae[t].append(mae)
        cv_rmse[t].append(rmse)
        cv_r2[t].append(r2)
        print(f"  {t:<18} {mae:>10.0f} {rmse:>10.0f} {r2:>8.3f}")

# ── CV Summary ───────────────────────────────────────────────────
print("\n" + "="*65)
print("AVERAGE ACROSS ALL 5 FOLDS")
print("="*65)
print(f"{'Target':<18} {'Avg MAE':>10} {'Avg RMSE':>10} {'Avg R2':>8}")
print("-"*50)
for t in targets:
    print(f"{t:<18} "
          f"{np.mean(cv_mae[t]):>10.0f} "
          f"{np.mean(cv_rmse[t]):>10.0f} "
          f"{np.mean(cv_r2[t]):>8.3f}")

# ══════════════════════════════════════════════════════════════════
# TRAIN FINAL MODEL ON ALL DATA
# ══════════════════════════════════════════════════════════════════

print("\n" + "="*65)
print("TRAINING FINAL MODEL ON ALL DATA")
print("="*65)

final_scaler = StandardScaler()
X_final      = final_scaler.fit_transform(X)

final_model = MultiOutputRegressor(
    XGBRegressor(
        n_estimators=500,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        n_jobs=-1
    )
)
final_model.fit(X_final, Y)
print("Final model trained on all data!")

# ── Final evaluation on last 60 days ─────────────────────────────
test_mask = df['Date'] >= df['Date'].max() - pd.DateOffset(days=60)
X_test_final = final_scaler.transform(df.loc[test_mask, features].values)
Y_test_final = df.loc[test_mask, targets].values
Y_pred_final = np.clip(final_model.predict(X_test_final), 0, None)

print(f"\n{'Target':<18} {'MAE':>10} {'RMSE':>10} {'R2':>8}")
print("-"*50)
for i, t in enumerate(targets):
    mae  = mean_absolute_error(Y_test_final[:, i], Y_pred_final[:, i])
    rmse = mean_squared_error(Y_test_final[:, i], Y_pred_final[:, i]) ** 0.5
    r2   = r2_score(Y_test_final[:, i], Y_pred_final[:, i])
    print(f"{t:<18} {mae:>10.0f} {rmse:>10.0f} {r2:>8.3f}")

# ── Save model files ─────────────────────────────────────────────
joblib.dump(final_model,  'generation_model.pkl')
joblib.dump(final_scaler, 'generation_scaler.pkl')
print("\nModel files saved!")

# ── Download ─────────────────────────────────────────────────────
from google.colab import files
files.download('generation_model.pkl')
files.download('generation_scaler.pkl')
print("Download started!")